import { Inter } from "next/font/google";
import Nav from "./(components)/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogging App",
  description: "Generated by Humza Qureshi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col h-screen max-h-screen">
        <Nav />
        <div className="flex-grow overflow-y-auto bg-slate-500 text-default-text">
          {children}
        </div>
      </div>
      </body>

    </html>
  );
}
